#!/usr/bin/env bash
# Script that installs the `nginx` on my server & configures it on port 80
# Update & Install the NGINX.
sudo apt-get update
sudo apt-get install nginx -y
# Make the the default directories & the default home page of the website.
sudo ufw allow 'Nginx Full'
sudo chown ubuntu /var/www/html
sudo rm -r /var/www/html/*
sudo touch /var/www/html/index.html
sudo chmod u+w /var/www/html/index.html
sudo echo "Hello World!" > /var/www/html/index.html
# Restart the NGINX.
sudo service nginx restart
